src/core/grid/exampleFlexRow.js
src/core/grid/exampleFlexRow.md
src/core/grid/flexCol.js
src/core/grid/flexRow.base.js
src/core/grid/index.js

This PR adds the existing functionality that we have developed on
quark-ui in styled component form!
For the `FlexRow`, simply importing the `FlexRow` css into your component
and it will automatically have styling applied the the element.
Adding override props to the component that implements `FlexRow` will
pass those down to the `FlexRow` styling. My hope is at some point in the
near future to automatically detect if a `FlexRow` is nested via context
so that we won't have to worry about the nested prop.
For the `FlexCol` things get a little more complex as we have to be able
to pass specific props to it. In order to keep a cleaner DOM structure,
the `FlexCol` component actually clones it's child element and applies
the sizing styles to the child and returns it. This allows for the …

Re-creating the flex grid from quark-ui

---

src/components/customerQuotes/__snapshots__/customerQuotes.test.js.snap
src/components/video/__snapshots__/backgroundVideo.test.js.snap
src/components/video/backgroundVideo.js
src/components/video/backgroundVideo.md
src/components/video/backgroundVideo.test.js
src/core/video/video.js

Due to an issue where our content was taller than our background video
we had some issues where the children of the tout were overflowing in
the Tout. This PR allows us to have two video files that are pulled in
when a specific breakpoint is reached. This paradigm is similar to how
we do backgroundImages in Mirage.

Making BackgroundVideo responsive

---

src/components/pressQuotes/pressQuotes.js

On really wide displays the centering was off for press quotes; this fixes that.

Fixes centering for press quotes styling

---

src/components/customerQuotes/__snapshots__/customerQuotes.test.js.snap
src/components/customerQuotes/customerQuotes.js
src/components/customerQuotes/defaultProps.js

Updates the `CustomerQuotes` component: adding in a signature that has the quotee & location, updated styling to match `PressQuotes` and adjusted padding/margins to work well with new styling.

Customer quotes w/ name, location & styling updates

---

src/components/pressQuotes/pressQuotes.js

This PR adds a reagion that renders out all of the press quotes and
hides the quotes that we render in and out from the screen reader. This
allows users with screen readers to navigate through the quotes without
any strange behavior due to the quotes being mounted and unmounted.

Adding screen reader region for accessibility

---

src/components/social-media/instagram.js
src/modules/social-media/__snapshots__/instagramRegion.test.js.snap

Currently when a screen reader hits the instafeed images, it spouts off
the link to the instagram photo (which is a huge string of random
characters) what we are doing now is adding the instagram caption as an
aria-label to the link that wraps the image so screen readers will now
have some context around the image.

Adding Instagram caption to link

---

src/components/pressQuotes/IconRow.js
src/components/pressQuotes/__snapshots__/pressQuotes.test.js.snap
src/components/pressQuotes/defaultProps.js
src/components/pressQuotes/pressQuotes.js
src/modules/forms/__snapshots__/DefaultSection.test.js.snap

[Delivers: #164644428 #164644184]
This PR addresses two issues.
* The screen reader has some pronunciation issues with the header and
some of the quotes. I updated an aria label for the header so that it
reads out: "What's the buzz?" and I fixed the quotes so that the L.A.
Times is rad out correctly.
* Updated the PressQuotes so that the timer gets reset when the chevrons
or logos are clicked.
* Touched up some styling issues with the chevrons so that the width
remains consistent.
* Cleaned up some code structure

Touching up some issues on the PressQuotes section

---

src/components/breakpoints/index.js
src/core/theme/breakpoints.js
src/core/theme/theme.js

Based off of a comment that @jrusso1020 had made in the breakpoint
components, we went back and converted the Breakpoint components to
utilize CSS instead of React Responsive. The components should hopefully
have the same functionality however, they should be able to work even if
they are server side rendered!

Making Breakpoint Component SSR Friendly

---

src/modules/header/header.js
src/modules/header/header.md
src/modules/header/index.js

This PR simply adds a component that renders out the DesktopHeader when
on a Desktop breakpoint and Mobile when not on a Desktop breakpoint.

Adding the responsive header component

---

src/templates/outfits/outfitDetail.js

This PR removes the width constraint on the out description pages. We now
constrain the width of the outfit information to a max-width of 500px
and remove the max width of the page from 1440px.

Removing the width contraint on outfit pages

---

src/components/header/status/status.js
src/components/header/status/status.md

[#166121742]
This PR simply adds another color option for the status banner component
that has a gentle animated rainbow gradiant background.

Adding another color for the status message

---

package-lock.json
package.json
src/components/contentful/image/contentfulImage.js
src/components/contentful/image/contentfulImage.md
src/components/contentful/image/contentfulImage.test.js
src/components/contentful/image/index.js
src/components/contentful/index.js
src/services/contentful.js
styleguide.config.js

This PR introduces Contentful as a development dependency to the Mirage
codebase. We also created a Contentful React component that allows
developers to make a call to Contentful to then get real data back from
the contentful service. Since Contentful is installed as a development
dependency it shouldn't be included when installing a later version of
Mirage thus creating conflicting version of Contentful. The Contenful
component itself is also not being exported as a component currently, if
we decide that it might be easier to utilize it as component then we
could include it in the main index.js export of Mirage.
This PR also includes the first example using the Contentful component
the ContentfulImage component. We pass the operation to `getAsset` and
the `id` of the image asset from: …

Introducing Contentful to Mirage

---

src/modules/persistent-cart/cartSidebar/cartSidebar.js

With this change we'll update the `CartSidebar` component so it displays the pricing test promotion so customers know they can get a 20% discount when they purchase 4 or more items.

Display pricing test promo in the cart sidebar

---

package-lock.json
package.json
src/modules/header/mobileNavigation/mobileNavigation.js
src/modules/header/mobileNavigation/mobileNavigation.md

With this change we'll wrap the bag icon on the mobile navigation to ensure the clickBag listener is
triggered when the customers actually click on the icon.
It seem like `<svg />` components don't respond to the `onClick` property, so we'll wrap the component in an anchor tag

Ensure the bag icon on mobile is clickable

---

src/core/typography/link/Link.base.js
src/modules/header/desktopNavigation/accountLinks/desktopAccountLinks.js

With this change we'll make sure that if we default to an anchor tag in the default renderLink function, it actually sets the href attribute, effectively taking the user where he/she needs to go.
We'll also make sure that the `renderLink` function is passed down to the account `SubMenu`.
https://www.pivotaltracker.com/story/show/166533136

Ensure default links work

---

src/components/social-media/instagram.js

Adds `alt` tag to animated Instagram illustration, to provide further context to screen readers.
Going to add documentation on how I tested this locally.
Please let me know if I'm missing anything.
Thanks Shawn for the assist!
https://pivotaltracker.com/n/projects/2089973/stories/164615825

[Fixes #164615825] Add alt tag to animated Instagram illustration

---

package-lock.json
package.json
src/components/couponCode/removeCouponCode.js

Fixes bug that prevents user from removing promotion.
Correctly references `BaseRemoveCouponCode`, which then displays on the page.
- https://www.pivotaltracker.com/n/projects/2089973/stories/166942152

[Fixes #166942152] Fix bug to remove promotion

---

package-lock.json
package.json
src/components/couponCode/removeCouponCode.js

Fixes bug that prevents user from removing promotion.
Correctly references `BaseRemoveCouponCode`, which then displays on the page.
I think original PR was somehow overwritten: https://github.com/rocketsofawesome/mirage/pull/108.
- [Delivers #166942152]
- https://www.pivotaltracker.com/n/projects/2089973/stories/166942152

166942152 Fix bug to remove promotion

---

src/core/grid/flexCol.js

This PR addresses an issue that appears to have been lingering around
since the FlecCol/FlexRow was introduced where the FlexCol component
didn't appear to have a large enough padding between columns when above
the tablet breakpoint. Currently the spacing is 5px on either side of a
FlexCol for all sizes, this change will increase that to 10px when the
device is tablet sized or larger.

Increase Flex Col Padding Tablet and larger

---

src/components/images/slider/slider.base.js
src/core/image/__snapshots__/inlineImage.test.js.snap
src/core/image/inlineImage.js
src/core/image/inlineImage.md
src/core/image/inlineImage.test.js
src/modules/productTile/productTile.base.js

[#167436130]
This PR adds the ability to lazy load images. If the `lazyLoad` prop is passed to the `InlineImage` we will not set the `src` attribute on the `img` element but will set a `data-src` attribute which can then be interacted with a HOC to load in images if the element is in the current viewport.

Inline Images can be Lazy Loaded

---

package-lock.json
package.json
src/modules/header/mobileNavigation/accountLinks/mobileAccountLinks.js
src/modules/header/mobileNavigation/mobileNavigation.js

Adds signing out to mobile menu.
Passes `signOut` function down to an `onClick` on `MobileLinkTop`.
- `thor` PR TBA
- [Fixes #167469094]
- https://www.pivotaltracker.com/n/projects/2089973/stories/167469094

[Fixes #167469094] Sign out from mobile menu

---

src/components/images/slider/slider.base.js

Removes `onLazyLoad` prop from sliders that are lazy loaded on the PLP pages. 
[Delivers #167436130]

[Fixes #167436130] Removes slider onLazyLoad

---

src/components/images/slider/slider.base.js
src/core/image/inlineImage.js

Gives styling `visibility: hidden` to photos that are not the current slick slider photo.
The bug is in the slick slider product images on the Thor PLPs where some photos show ~1px on the left or right side of the next photo in the slider. By removing the visibility of the non-current photo, it doesn't impact the slider position and fixes the places where this is an issue.
- [Delivers #167408546]
- https://www.pivotaltracker.com/n/projects/2089973/stories/167408546

[Fixes #167408546] Fix visibility of secondary photos

---

src/components/images/slider/slider.js

[#167476520]
Adding a preset height for the images that are lazy loaded in. My hope
is that this might help with the scroll position issue that we are
witnessing on the PLP.

Adding a default height for lazy-loaded images

---

package-lock.json
package.json
src/core/typography/H1.js
src/core/typography/__snapshots__/H1.test.js.snap

Allows `H1` styled component to accept line-height props for desktop and mobile.
- [Delivers #167623464]
- https://www.pivotaltracker.com/n/projects/2089973/stories/167623464

[Fixes #167623464] Let H1 take line-height props

---

package-lock.json
package.json
src/core/icons/Logo/Logo.base.js
src/core/theme/mediaQueries.js

Makes the iPhone 5 navigation logo smaller so that the cart indicator icon will not get cut off by the screen.
This change will make the size of logo on Thor match Quark UI.
The `phone` media query width is modified so that the iPhone 5 can be styled separately from the later version iPhones as we can do in Quark UI. `breakpointsVerbose.abovePhone` (not previously used) will target devices 321px wide and larger.
Dependent on updating Mirage version on Thor.
- [Fixes #167856738]
- https://www.pivotaltracker.com/story/show/167856738

[Fixes #167856738] Makes iPhone 5 navigation logo smaller

---

package-lock.json
package.json
src/components/productTile/colorPicker/colorPicker.md
src/components/productTile/colorPicker/colorPicker.test.js
src/components/productTile/colorPicker/defaultProps.js
src/modules/productTile/colorPicker/colorsInterface.base.js

Updates Cloudinary transformation for ColorPicker (color swatches). New transformation `swatch_v2` pulls sample swatch relative to the center of the shot. This transformation is getting better results overall than the original `swatch` transformation (less shadows and white backgrounds). See comparison:
Bomber swatches are a lot better, but still can't accommodate the on-model jean shots without messing up a lot of other swatches. We might have to do another fix for outlier shots.
I made the comparison on the Mirage local `colorPicker.md` so we can play around with ColorPicker transformations in the future if we need to, but let me know if you think I should take this down.
Dependent on Thor PR
- [#167857176]
- https://www.pivotaltracker.com/story/show/167857176

[#167857176] Update Cloudinary transformation for ColorPicker

---

package-lock.json
package.json
src/components/images/slider/slider.base.js
src/core/image/inlineImage.js

Hides noncurrent item cards on PLP.
Basically Katie's PR with very minor changes: https://github.com/rocketsofawesome/mirage/pull/140.
This was reverted in the past due to side effect, where mobile users have to tap on item twice (after sliding) to get to PDP.
This seems to already be on production, so we can fix in another ticket.
- [Finishes #167408546]
- https://www.pivotaltracker.com/n/projects/2089973/stories/167408546

[#167954762] Hide noncurrent item cards on PLP

---

package-lock.json
package.json
src/components/images/slider/slider.base.js

Lets mobile user tap once (instead of twice) to navigate to PDP, after sliding on PLP.
Hacky solution inspired from open issue on `react-slick`.
Have to wait for for official fix, or move away from `react-slick`.
Former won't happen anytime soon!
- [Finishes #168382171]
- https://www.pivotaltracker.com/n/projects/2089973/stories/168382171

[#168382171] Let mobile user tap once to navigate to PDP

---

package-lock.json
package.json
src/modules/productTile/colorPicker/colorsInterface.base.js
src/modules/productTile/colorPicker/defaultProps.js
src/utils/index.js
src/utils/swatchUrl.js
src/utils/swatchUrl.test.js

Create helper function `swatchUrl` to get the color swatch URL from Cloudinary.
`swatchUrl` will check for the presence of a custom swatch for the given colorway before using the default transformation on the 'front' shot.
Requires commits in Canon, Quark, and Thor to complete the story.
- [Finishes #168383382] 
- https://www.pivotaltracker.com/story/show/168383382

[#168383382] Make color picker use custom swatch if provided

---

package-lock.json
package.json
src/core/typography/H1.js
src/core/typography/H1.test.js
src/core/typography/__snapshots__/H1.test.js.snap

Permits styled H1 component to receive `letterSpacing` prop.
This change will allow us to style the H1 in Thor to match the styling of an H2.
Depends on PR in Thor.
- [Finishes #168468228]
- https://www.pivotaltracker.com/story/show/168468228

[#168468228] Permit styled H1 to receive letterSpacing prop

---

package-lock.json
package.json
src/components/confetti/Confetti.js

With this change we'll update how we set refs on the `Confetti` component so we ensure backwards compatibility with React 15 used by quark-ui.

Use callback refs to ensure backwards compatibility

---

package-lock.json
package.json
src/modules/persistent-cart/persistentCartProduct/persistentCartProduct.js

Calls `hideCartSidebar` on product click.
Moves `hideCartSidebar` from `ImageLink` level to `img` level.
- [#169260976]
- https://www.pivotaltracker.com/n/projects/2089973/stories/169260976

[#169260976] Call hideCartSidebar on product click

---

package-lock.json
package.json
src/modules/persistent-cart/cartSidebar/cartSidebar.js

Removes free shipping text from `cartSidebar`.
Fixes styling of "Is this a gift?" link per Zeplin specs.
- [#168985573]
- https://www.pivotaltracker.com/story/show/168985573

[#168985573] Remove free shipping text and fix styling of gift link

---

package-lock.json
package.json
src/modules/persistent-cart/cartSidebar/cartSidebar.js

Adds query param indicating order is a gift when customer clicks on "Is this a gift?" in the cart.
Dependent on PRs in Quark UI and Thor and changes made to `/checkout` in Quark UI to start with gift option checked.
[ch5617]

[ch5617] Add query params to GiftLink

---

package-lock.json
package.json
src/modules/productTile/index.js
src/modules/productTile/productPrice/index.js
src/modules/productTile/productPrice/productPrice.js
src/modules/productTile/productPrice/productPrice.test.js
src/modules/productTile/productTile.base.js
src/modules/productTile/productTile.js
src/utils/pricing.js

Displays original price next to sale price on PLP product tiles
PR on Thor
- [#168811273]
- https://www.pivotaltracker.com/story/show/168811273

[#168811273] Display original price next to sale price on PLP product tiles

---

src/modules/persistent-cart/persistentCartProduct/persistentCartProduct.js

Shows the strikethrough price in cart for BF/CM sale items.
Update Mirage version in Quark UI and Thor
[ch5625]
https://app.clubhouse.io/rockets/story/5625/customer-reads-that-black-friday-cyber-monday-sale-item-is-final-sale-in-checkout-page

[ch5625] Display strikethrough prices in cart for BF/CM sale

---

package-lock.json
package.json
src/components/giftModal/GiftModal.js

Removes FINAL SALE copy from gifting modal.
Updates Mirage to `0.1.415`.
- [ch5975]
- https://app.clubhouse.io/rockets/story/5975/customer-reading-gifting-promotional-pop-up-doesn-t-see-final-sale-language

[ch5975] Remove FINAL SALE copy from gifting modal

---

package-lock.json
package.json
src/components/giftModal/GiftModal.js

Removes asterisk from gifting modal.
Updates `@rocketsofawesome/mirage` to `0.1.416`.
- [ch5975]
- https://app.clubhouse.io/rockets/story/5975/customer-reading-gifting-promotional-pop-up-doesn-t-see-final-sale-language

[ch5975] Remove asterisk from gifting modal

---

package-lock.json
package.json
src/modules/persistent-cart/cartSidebar/cartSidebar.js

Enables 'KEEP SHOPPING' button in bag to scroll to complete the look on PDP pages.
https://github.com/rocketsofawesome/thor/pull/222
[ch5639]
https://app.clubhouse.io/rockets/story/5639/customer-adds-item-to-bag-from-pdp-continues-shopping-should-be-anchored-to-complete-the-look-product-reccs

[ch5639] Pass scrollKeepShopping callback to cartSidebar

---

package-lock.json
package.json
src/modules/persistent-cart/cartSidebar/cartSidebar.md
src/modules/productTile/colorPicker/colorsInterface.js
src/modules/productTile/defaultProps.js
src/modules/productTile/productPrice/productPrice.js
src/modules/productTile/productTile.base.js
src/modules/productTile/productTile.js
src/modules/productTile/productTile.md

With this change we'll start displaying the evergreen promotional price inside product tiles, hopefully this will prompt users to add more items to their cart.
https://app.clubhouse.io/rockets/story/5898/customer-can-see-price-of-item-with-evergreen-promo-applied-on-item-cards

Display the evergreen promotional price on ProductTiles

---

package-lock.json
package.json
src/components/inputs/InputSmall/InputSmall.js
src/components/inputs/InputSmall/InputSmall.md
src/components/inputs/XCheckbox/XCheckbox.js

Changes color of input text for `InputSmall`.
Adjusts `XCheckbox` PropTypes to have required props for redux form component or regular React component.
Update Mirage version on Thor
[ch5968]
https://app.clubhouse.io/rockets/story/5968/guests-can-request-to-get-alert-when-items-are-back-in-stock

[ch5968] Fix styling on InputSmall and PropTypes on XCheckbox

---

package-lock.json
package.json
src/modules/contentful/landing/landing.js
src/modules/contentful/touts/contentfulSplitTout.base.js
src/modules/contentful/touts/contentfulTout.base.js
src/modules/contentful/touts/contentfulTout.js

Makes `hero` with `destination` clickable.
Navigates programmatically (without `a` element): `window.location.href = destination`.
Maintains default `div` layout if `destination` present on `hero`, instead of replacing with `a` element. (The latter breaks styling.)
- [ch6339]
- https://app.clubhouse.io/rockets/story/6339/ability-for-customer-to-click-on-homepage-hero-image

[ch6339] Make hero with destination clickable

---

package-lock.json
package.json
src/modules/contentful/touts/contentfulTout.base.js

Adds `segmentHeroClicked` to `BaseContentfulTout`.
Adds `destination` property to `segmentHeroClicked`.
- [ch6470]
- https://app.clubhouse.io/rockets/story/6470/hero-clicked-event-fires-when-customer-clicks-hero-image

Add segmentHeroClicked to BaseContentfulTout

---

package-lock.json
package.json
src/modules/contentful/touts/contentfulTout.js

Reduces padding below clickable hero on mobile.
Swaps `padding-bottom` with `margin-bottom` in that scope.
- [ch6493]
- https://app.clubhouse.io/rockets/story/6493/mobile-customer-sees-more-content-in-homepage-viewport-when-only-1-button-is-used-in-hero

[ch6493] Reduce padding below clickable hero on mobile

---

src/modules/contentful/slider/contentfulSlider.js

With this change we'll display the dot indicator within the ContentfulSlider component so users can know which slide they're currently watching and how many slides there are.
https://app.clubhouse.io/rockets/story/6560/customer-can-see-how-many-stories-are-in-homepage-hero-carousel

Display dot indicator within the ContentfulSlider

---

src/modules/contentful/slider/contentfulSlide.js
src/modules/contentful/slider/contentfulSlider.js
src/modules/contentful/slider/defaultProps.js

With this change we'll display any buttons associated with contentful slides so we can add CTAs to our slides.
https://app.clubhouse.io/rockets/story/6564/customer-can-navigate-to-content-from-homepage-hero

Display buttons inside of contentful slides

---

src/modules/contentful/slider/contentfulSlide.js
src/modules/contentful/slider/contentfulSlider.js
src/modules/contentful/slider/defaultProps.js

With this change we'll allow customers to click anywhere on a slide to navigate, the image will only be clickable when the URL field is set on contentful.
https://app.clubhouse.io/rockets/story/6564/customer-can-navigate-to-content-from-homepage-hero

Allow users to click anywhere on a slide to navigate

---

package-lock.json
package.json
src/modules/contentful/slider/contentfulSlide.js
src/modules/contentful/slider/contentfulSlider.js

Adds `segmentHeroClicked` to `ContentfulSlider`.
Includes `asset` (image URL), `destination`, `name`, and `position`.
- [ch6575]
- https://app.clubhouse.io/rockets/story/6575/add-asset-name-position-and-number-of-slides-attributes-to-hero-clicked-event

[ch6575] Add segmentHeroClicked to ContentfulSlider

---

package-lock.json
package.json
src/modules/contentful/slider/contentfulSlider.js

Adds `segmentHeroViewed` to `ContentfulSlider`.
Triggers `segmentHeroViewed` on initial view and subsequent views (e.g., transition to next slide).
- [ch6594]
- https://app.clubhouse.io/rockets/story/6594/create-hero-viewed-event-with-asset-name-position-and-number-of-slides-attributes

[ch6594] Add segmentHeroViewed to ContentfulSlider

---

package-lock.json
package.json
src/modules/contentful/slider/contentfulSlide.js
src/modules/contentful/slider/contentfulSlider.js

Prevents triggering of `segmentHeroClicked` on drag.
Activates `segmentHeroClicked` only on regular click.
- [ch6575]
- https://app.clubhouse.io/rockets/story/6575/add-asset-name-position-and-number-of-slides-attributes-to-hero-clicked-event

[ch6575] Prevent segmentHeroClicked on drag

---

package-lock.json
package.json
src/modules/contentful/slider/contentfulSlider.js

Prevents some mobile Safari users from clicking `ContentfulSlider` twice (after slide) to navigate to destination.
Sets `this.slider.innerSlider.clickable` to `true` at end of `afterChange`.
- [ch6678]
- https://app.clubhouse.io/rockets/story/6678/some-customers-have-to-click-hero-slide-twice-to-be-directed-to-destination

[ch6678] Prevent some mobile Safari users from clicking ContentfulSlider twice

---

package-lock.json
package.json
src/modules/persistent-cart/cartSidebar/cartSidebar.js
src/modules/persistent-cart/persistentCartProduct/persistentCartProduct.js
src/modules/persistent-cart/persistentCartProductList/persistentCartProductList.js

Adds `segmentProductRemoved` to `PersistentCartProduct`.
Sends `item` into `segmentProductRemoved`, which has context of `products`, `colorways`, and `variants`.
- [ch6441]
- https://app.clubhouse.io/rockets/story/6441/fix-product-removed-event

[ch6441] Add segmentProductRemoved to PersistentCartProduct

---

package-lock.json
package.json
src/components/footer/Footer.js

Customer Sees Returns Link on Homepage Underneath Help Link
As a customer, I want to easily find returns information on the homepage so I can return unwanted items.
Acceptance Criteria
Returns link appears directly beneath Help link
Returns link links to: https://support.rocketsofawesome.com/hc/en-us/articles/360031271434-How-do-returns-work-for-my-online-order-
https://app.clubhouse.io/rockets/story/6709/customer-sees-returns-link-on-homepage-underneath-help-link

Customer Sees Returns Link on Homepage Underneath [ch6709]

---

package-lock.json
package.json
src/modules/persistent-cart/cartSidebar/cartSidebar.js
src/modules/persistent-cart/persistentCartProduct/persistentCartProduct.js
src/modules/persistent-cart/persistentCartProductList/persistentCartProductList.js

Sends `finalSaleOn` prop to cartSideBar, which determines whether to show "FINAL SALE" copy below sale items in bag.
PR in Thor and Quark UI
[ch6741]
https://app.clubhouse.io/rockets/story/6741/make-an-env-variable-for-final-sale-language
[ch6742]
https://app.clubhouse.io/rockets/story/6742/customer-only-sees-final-sale-label-logic-on-sale-items-that-are-final-sale

[ch6741] Send final sale prop to cartSideBar

---

package-lock.json
package.json
src/modules/productTile/productPrice/productPrice.js

Adds highlighter background color to evergreen promo on product tiles.
[ch6757]
https://app.clubhouse.io/rockets/story/6757/customers-see-evergreen-promo-price-highlighted-in-yellow

Ch6757 plp highlighter

---

package-lock.json
package.json
src/components/header/promos/shop/persistantPricing/persistantPricing.js
src/modules/persistent-cart/cartSidebar/cartSidebar.md

Adjusts `PersistantPricing` (rotating messages inside the eyebrow banner) to receive two messages instead of three.
[ch6763]
https://app.clubhouse.io/rockets/story/6763/customers-know-about-the-sale-via-the-site-sticky-banner

[ch6763] Adjust PersistantPricing to receive two messages

---

package-lock.json
package.json
src/modules/persistent-cart/cartSidebar/cartSidebar.js

Adds the keep shopping treatment (scroll down to complete the look or recommended products) when a user adds to cart and clicks the "X" or the overlay to exit cartSidebar.
[ch6767]
https://app.clubhouse.io/rockets/story/6767/after-customer-adds-to-bag-via-pdp-and-exits-bag-they-see-product-recommendations

[ch6767] Add keep shopping cart logic to closing cartSidebar

---

package-lock.json
package.json
src/modules/productTile/productTile.base.js
src/modules/productTile/productTile.md

With this change we'll tweak the ProductTile component so the onQuickView callback receives information about the colorway that is currently in display on the tile.
This will allow us to display the right colorway when the quick view modal is opened.

Ensure the current colorway is used for quick view

---

package-lock.json
package.json
src/components/inputs/Checkbox/Checkbox.js
src/core/image/inlineImage.js
src/modules/productTile/productTile.base.js

With this change we'll allow customers browsing our site on their mobile devices to access quick view by tapping on the slider of each product tile. Desktop users will only be able to access quick view by clicking on the quick view button which will only be visible in desktop.
https://app.clubhouse.io/rockets/story/6847/mobile-customer-sees-quickview-after-tapping-the-product-tile-once

Allow mobile customers to view quick view with a single tap

---

package-lock.json
package.json
src/modules/outfits/outfitSizePicker/outfitSizePicker.js
src/modules/productTile/defaultProps.js
src/modules/productTile/productPrice/productPrice.js

Adds percent discount next to the crossed out original price on product tiles.
PRs on Quark (https://github.com/rocketsofawesome/quark/pull/1897) and Thor
[ch6819]
https://app.clubhouse.io/rockets/story/6819/customers-see-percent-discount-off-on-sale-item-cards

[ch6819] Add percent discount to product tiles

---

src/components/images/slider/slider.base.js
src/modules/productTile/productTile.base.js

Adds the Link component back in product tiles on laptop screen width.
[ch6854]
https://app.clubhouse.io/rockets/story/6854/desktop-customer-can-open-product-tiles-in-new-tabs

Allow open in new tab for product tiles on laptop screen width

---

package-lock.json
package.json
src/components/inputs/XCheckbox/X.base.js

With this change we'll replace the usage of the React.Fragment with the <g> element which should be compatible with older React apps (i.e quark-ui).

Replace React.Fragment with a backwards-compatible element

---

package-lock.json
package.json
src/modules/contentful/productQuartet/productQuartet.js

Passes evergreen promo props to the ProductTiles in ProductQuartet.
[ch6952]
https://app.clubhouse.io/rockets/story/6952/customer-sees-evergreen-promotion-as-6-for-20

[ch6952] Fix evergreen promo in product quartet

---

package-lock.json
package.json
src/core/icons/Spinner/GraySpinner.js
src/core/theme/colors.js

Makes the GraySpinner a darker gray color for visibility when changing size and quantity of line items (in checkout and bag).
We are not actively using the GraySpinner anywhere on the site, so I made the color change to this existing component.
[ch7010]
https://app.clubhouse.io/rockets/story/7010/customer-sees-darker-loading-indicator-when-changing-size-or-quantity

[ch7010] Make gray spinner a darker gray

---

package-lock.json
package.json
src/core/grid/flexCol.js
src/core/grid/flexRow.base.js
src/core/grid/flexRow.js

With this change we'll fix a couple of warnings thrown when using the `FlexRow` component and make sure that the align
property works as expected.

Fix FlexRow warnings and align functionality

---

package-lock.json
package.json
src/core/grid/flexCol.base.js
src/core/grid/flexRow.base.js
src/core/typography/link/Link.base.js

With this change we'll make sure that `Links` are not underlined when they are hovered, this was being added by the default
bootstrap styles which are still present in some of the quark-ui pages.
This change will also fix some warnings associated with the FlexCol component.

Fix link styling and warnings related to the FlexCol component

---

package-lock.json
package.json
src/core/theme/mediaQueries.js
src/core/typography/H1.test.js

`FlexRow` uses different margins for `abovePhoneMax` media query. This commit fixes the `above` queries to only include wider widths than the device size. So `abovePhoneMax` will not include phones with the widest 414px width.
This previously caused issues where iPhone plus devices could show styling meant for larger devices.
[ch7664]
https://app.clubhouse.io/rockets/story/7664/existing-subscribers-see-new-page-to-change-their-box-sizes

[ch7664] Fix above media query to be larger max width than the selected device

---

package-lock.json
package.json
src/components/header/desktopHeader/headerLink/headerLink.js
src/core/typography/H1.js
src/core/typography/H2.js
src/core/typography/H3.js
src/core/typography/H4.js
src/core/typography/H5.js
src/core/typography/H6.js
src/core/typography/Label.js

With this change we'll update the prop type of the children property passed to heading elements to be PropTypes.node as
it allows a lot more flexibility and suits it better.

Update the children prop type for heading elements

---

package-lock.json
package.json
src/components/inputs/Buttons/Button/ButtonLink.js

With this change we'll make sure that ButtonLinks don't change their styling when hovering over them in quark-ui. Since
it's still using Bootstrap in certain parts of the application, our ButtonLinks are changing color when the user hovers over them, which is not what we want.

Ensure button links are compatible with Bootstrap styles

---

package-lock.json
package.json
src/components/header/desktopHeader/accountLinks/subMenu.js
src/modules/header/desktopNavigation/accountLinks/desktopAccountLinks.js
src/modules/header/desktopNavigation/accountLinks/desktopAccountLinks.test.js
src/modules/header/desktopNavigation/desktopNavigation.js
src/modules/header/mobileNavigation/mobileNavigation.js

Adds "Rockets Reverse" link to desktop and mobile navigation on Thor pages.
PR on Quark UI
[ch7841]
https://app.clubhouse.io/rockets/story/7841/subscriber-sees-rockets-reverse-in-nav-on-mobile
[ch7843]
https://app.clubhouse.io/rockets/story/7843/subscriber-sees-rockets-reverse-in-nav-on-desktop

Add navigation links for /rockets-reverse on desktop and mobile

---

package-lock.json
package.json
src/core/theme/mediaQueries.js

Adds a new breakpoint `aboveIncluding` so we can include all pixel widths if we want to use different elements above and below a breakpoint (missing one pixel width).
Example:
`aboveTablet` includes min width 769
`aboveIncludingTablet` includes min width 768
`belowTablet` includes widths max width 767
`belowTablet` and `aboveIncludingTablet` together will cover all screen widths.

Add aboveIncluding breakpoint for mediaqueries

---

package-lock.json
package.json
src/components/social-media/instagram.js

This PR adds the Yotpo Instagram carousel to the shop homepage in place of the broken Instagram feed.
[ch7902]
https://app.clubhouse.io/rockets/story/7902/customers-see-instagram-photos-on-shop-landing-page-again

Ch7902 instagram feed homepage

---

package-lock.json
package.json
src/modules/persistent-cart/persistentCartProduct/persistentCartProduct.js

This PR changes the color of product error messages in the persistent cart. "Out of stock." and "Only x items left" will be displayed in red so they are more noticeable to the customer.
https://app.clubhouse.io/rockets/story/7949/ecomm-customer-understands-why-they-can-t-check-out

[ch7949] Display out of stock and not enough quantity error messages in red

---

package-lock.json
package.json
src/components/social-media/instagram.js

This commit will assign the shop homepage a different Yotpo Instagram photo gallery from the gallery that is on the subscription homepage. This way we will be able to make visual adjustments to the galleries separately via the Yotpo dashboard.
We are also increasing padding around the Instagram feed on larger screen sizes.
https://app.clubhouse.io/rockets/story/7902/customers-see-instagram-photos-on-shop-landing-page-again

Use separate Yotpo gallery for the shop homepage and increase padding

---

package-lock.json
package.json
src/modules/header/header.js
src/modules/searchModal/searchModal.js

This PR prevents the Yotpo Instagram widget arrows from overlapping the header and dropdown menu.
https://app.clubhouse.io/rockets/story/8025/shop-landing-page-instagram-module-overlaps-with-mobile-hamburger-menu

[ch8025] Adjust z-index of header to work with Yotpo Instagram widget

---

package-lock.json
package.json
src/components/productTitle/ProductTitle.js

This PR solves an issue where we were evaluating whether a price is less than the original price to confirm it's on sale, but because the prices were strings the logic was sometimes faulty. We are now converting to numbers before using any operators.
example for $5 sale items: "5.0" < "19.5" returns false, but we want to confirm that $5 is less than $19.50
https://app.clubhouse.io/rockets/story/8027/pdps-of-5-bonanza-items-should-show-full-price-discount

[ch8027] Show original price on PDPs with  sale items

---

package-lock.json
package.json
src/components/images/slider/slider.base.js
src/modules/productTile/productTile.base.js

With this change we'll make sure that images in the `ProductTile` slider match the currently selected colorway. Basically the image wouldn't change before because we were spreading all of the props from ProductTile and passing them to the Slider, which caused the `lazyLoad` prop to override the value of the `lazyLoad` key coming from `state`.
Since `lazyLoad` was true, we were attempting to lazy load the images for the newly selected colorway, which would only happen if the user scrolled. With this change we'll stop spreading props and passing them to the Slider which should make it obvious which properties it's receiving at any point in time and fix the bug.
https://app.clubhouse.io/rockets/story/7385/desktop-customer-can-t-view-additional-colorway-photo-on-select-items

Ensure that images on the ProductTile slider match the current colorway

---

package-lock.json
package.json
src/components/datepicker/Datepicker.js

With this change we'll fix a bug that prevented datepickers to pass the correct value to the `onChange` callback when an
`initialValue` had been given.

Ensure datepickers update correctly when an initialValue is given

---

src/components/datepicker/Datepicker.js
src/components/inputs/Select/Select.js
src/components/inputs/Select/Select.md

This PR adds a mini style variant to the regular select component for use in the quiz checkout form and elsewhere.
https://app.shortcut.com/rockets/story/9430/mini-subscription-lead-sees-styling-on-billing-shipping-screen

Add mini styling variant to regular select component

---

src/components/curvedText/curvedText.js
src/components/inputs/Checkbox/Checkbox.js
src/components/inputs/Checkbox/Checkbox.md
src/components/inputs/Checkbox/Rect.base.js
src/core/typography/H1.js
src/core/typography/H2.js
src/core/typography/Label.js
src/core/typography/Label.md

This PR adds a color prop to H2, Label, CurvedText, and ensures that we can control the colors for checkboxes and their associated labels. These changes are needed to support the different stylings we're trying to implement in mini. 
https://app.shortcut.com/rockets/story/9430/mini-subscription-lead-sees-styling-on-billing-shipping-screen

Add color props to more text components

---

src/core/grid/flexRow.js

This PR adds `wrap` and `columnGap` props to the `flexRow` component to allow for more explicit styling of children `flexCols`.

Add wrap and column gap props to flexRow component

---

package-lock.json
package.json
src/modules/header/desktopNavigation/desktopNavigation.js
src/modules/header/mobileNavigation/mobileNavigation.js
src/utils/shotSorter.js

With this change we'll update the desktop and mobile navigation components so they use relative paths instead of absolute paths, this makes links protocol agnostic which should make them more flexible.
We'll also export the sortShots function as it is used in a ton of different places (PLP, PDP, product tiles, etc.) being able
to import this function will help reduce duplication.

Use relative paths for navigation

---

src/modules/header/desktopNavigation/defaultProps.js
src/modules/header/desktopNavigation/desktopNavigation.js
src/modules/header/mobileNavigation/defaultProps.js
src/modules/header/mobileNavigation/mobileNavigation.js
src/modules/header/mobileNavigation/mobileNavigation.md

This PR removes the links that were meant to direct to mini starter kits since we have deprioritized them for now.

Hide links supporting mini starter kits from nav

---

src/components/addToBagState/AddToBagState.js

This PR addresses a bug in which clicking "Add to Bag" on PDPs loaded via client-side nagivating would duplicate the last item added to your cart. Because `sizeSelected` and `sku` are treated as internal pieces of state in this component, their old values would persist even when the `selectedColorway` changed. By resetting these state values when `selectedColorway` changes, we ensure that the previous item is not added to their cart again.
https://app.shortcut.com/rockets/story/9746/adding-a-recommended-item-to-bag-duplicates-existing-item-in-cart

Update Product Sku in AddToBagState Component When Client-Side Navigating
