src/core/grid/__snapshots__/grid.test.js.snap, src/core/grid/__snapshots__/sizer.test.js.snap, src/core/grid/grid.js, src/core/grid/grid.md, src/core/grid/index.js, src/core/grid/sizer.js, src/core/grid/sizer.test.js, src/core/image/sizes.base.js, src/core/index.js, src/core/theme/gridSettings.js
This PR adds the updated `Grid` and `Sizer` components to the codebase.
=> Adding Grid and Sizer components

src/renderer.js, src/renderer.md
This PR adds the holy mother of rendering components. What this
component does is take a structured JSON data object, and parses it to
figure out what component should be rendered out, as well as it's
children.
=> Adding the top level Recursive Renderer

src/core/image/backgroundImage.js, src/core/image/backgroundImage.md
There was an issue that crept in that I was not aware of but setting the
position of the children of the `backgroundimage` component to position
absolute caused the sizeMe component not to update.
=> Fixing background not changing issue

src/components/social-media/__snapshots__/instagram.test.js.snap, src/components/social-media/instagram.js, src/modules/social-media/__snapshots__/instagramRegion.test.js.snap
Add a gif to our instagram region
=> add instagram gif

src/components/customerQuotes/__snapshots__/customerQuotes.test.js.snap, src/components/customerQuotes/customerQuotes.js, src/components/social-media/__snapshots__/instagram.test.js.snap, src/modules/social-media/__snapshots__/instagramRegion.test.js.snap
This PR adds the two confetti gifs to the CustomerQuotes component
=> Adding Confetti to CustomerQuotes

package-lock.json, package.json, src/components/pressQuotes/__snapshots__/pressQuotes.test.js.snap, src/components/pressQuotes/defaultProps.js, src/components/pressQuotes/pressQuotes.js, src/components/video/__snapshots__/backgroundVideo.test.js.snap, src/components/video/backgroundVideo.js
Uses CSSTransitionGroup for fade in/fade out to avoid timer & render sync issues. Resizing press icons, making them smaller & changed order of quotes.
=> PressQuotes animation fix & quote styling updates

src/components/pressQuotes/pressQuotes.js
fixing spacing, mobile view, icons, margin and flex issues.
ty @mealeyst !
=> PressQuotes spacing/mobile/icons fix

src/components/pressQuotes/pressQuotes.js, src/core/icons/press/PressIcon.js
Have them match the actual color of the quote.
=> Updating colors on press quotes icons

package-lock.json, src/components/video/__snapshots__/backgroundVideo.test.js.snap, src/components/video/backgroundVideo.js, src/components/video/backgroundVideo.md, src/core/video/__snapshots__/Video.test.js.snap, src/core/video/video.js, src/core/video/video.test.js
Add a fallback image for mobile an desktop backgroundVideo so if he
video can't load we have a fallback image.
=> Add fallback images to backgroundVideo component

package-lock.json, package.json, src/components/social-media/__snapshots__/instagram.test.js.snap, src/components/social-media/instagram.js, src/modules/social-media/__snapshots__/instagramRegion.test.js.snap, src/setupTests.js
Add in a slider and styles for the instagramRegion that we will use on
the shop homepage on mobile.
=> Add instagramRegion mobile styles

src/components/aboutUs/__snapshots__/aboutUs.test.js.snap, src/components/aboutUs/aboutUs.js, src/components/customerQuotes/__snapshots__/customerQuotes.test.js.snap, src/components/customerQuotes/customerQuotes.js, src/components/customerQuotes/defaultProps.js, src/components/pressQuotes/pressQuotes.js, src/modules/social-media/__snapshots__/instagramRegion.test.js.snap, src/modules/social-media/instagramRegion.js
Quick copy change & decreasing H1 header size for mobile.
=> Dashes for commas, Header size decrease

src/components/customerQuotes/customerQuotes.js
Touching up the CustomerQuotes component to fix the issue where the
quotes would sometimes flicker when they were changed. I also tweaked
the confetti animation so that it plays as soon as the quote is
switched.
=> Fixing the flickering for customer quotes

src/components/customerQuotes/__snapshots__/customerQuotes.test.js.snap, src/components/customerQuotes/customerQuotes.js
Adding a section to the customer quotes and hiding the carousel from the
screen reader. This allows for the screen reader to navigate through the
quotes without having to wait for the carousel to render a quote.
=> Adding a screen reader section

src/components/social-media/instagram.js, src/modules/social-media/defaultProps.js, src/modules/social-media/instagramRegion.js
This PR adds some accessibility labels for the copy and hiding the phone illustration from the screen reader.
=> Addressing accessibility in instagram region

src/templates/looks/lookDetail.js
=> Updating the LookDetail Template

src/modules/looks/lookSizePicker/lookSizePicker.js, src/modules/looks/lookSizePicker/lookSizePicker.md, src/templates/looks/defaultProps.js, src/templates/looks/lookDetail.js
This PR adds the ability to link to the Product Description Page in the
Look Size Picker.
=> Adding the ability to link to Product

package-lock.json, package.json, src/modules/forms/sizePicker/__snapshots__/sizePicker.test.js.snap, src/modules/forms/sizePicker/sizePicker.js, src/modules/header/desktopNavigation/__snapshots__/desktopNavigation.test.js.snap, src/modules/header/desktopNavigation/accountLinks/__snapshots__/desktopAccountLinks.test.js.snap, src/modules/looks/lookSizePicker/__snapshots__/lookSizePicker.test.js.snap, src/modules/looks/lookSizePicker/lookSizePicker.js, src/templates/looks/lookDetail.js, src/templates/looks/lookDetail.md
=> Outfits changes

package-lock.json, package.json, src/modules/looks/lookSizePicker/__snapshots__/lookSizePicker.test.js.snap, src/modules/looks/lookSizePicker/lookSizePicker.js
=> Styling tweaks for size picker

src/components/header/index.js, src/components/header/promos/index.js, src/components/header/promos/shop/index.js, src/components/header/promos/shop/persistantPricing/index.js, src/components/header/promos/shop/persistantPricing/persistantPricing.js, src/components/header/promos/shop/persistantPricing/persistantPricing.md, src/components/header/promos/shop/persistantPricing/persistantPricing.test.js, src/components/header/status/status.js, src/components/header/status/status.md
This Pull Request adds the rotating banner message for the shop promotion
=> Adding the rotating promotion to mirage

package-lock.json, package.json, src/core/typography/H4.js, src/core/typography/__snapshots__/H4.test.js.snap, src/modules/header/desktopNavigation/__snapshots__/desktopNavigation.test.js.snap, src/modules/header/desktopNavigation/megaMenu/__snapshots__/megaMenuSection.test.js.snap, src/modules/images/__snapshots__/gallery.test.js.snap, src/modules/images/gallery.js, src/modules/outfits/outfitCards/outfitCards.js, src/modules/touts/splitTout/__snapshots__/splitTout.test.js.snap, src/templates/outfits/outfitDetail.js, src/templates/outfits/outfitsListing.js, src/templates/outfits/outfitsListing.md
[Delivers: #166162423, #166162346, #166163169, #166162146, #166162056]
This PR addresses some of the styling issues that Emily had identified
as well as pass a smaller image to the mobile slider gallery.
=> Updating spacing and image optimization

src/components/header/promos/shop/persistantPricing/persistantPricing.js
=> Updating the animation and text of the promo

src/components/video/__snapshots__/backgroundVideo.test.js.snap, src/components/video/backgroundVideo.js, src/components/video/backgroundVideo.md, src/components/video/backgroundVideo.test.js, src/core/video/__snapshots__/Video.test.js.snap, src/core/video/video.js, src/core/video/video.md
=> Reverting the videos to a later version

src/components/header/desktopHeader/headerLink/headerLink.js, src/components/header/mobileHeader/links/mobileLinkSecondary.js, src/components/header/mobileHeader/links/mobileLinkTop.js, src/components/sections/defaultProps.js, src/core/icons/BagIcon.js, src/core/typography/H4.js, src/modules/header/desktopNavigation/__snapshots__/desktopNavigation.test.js.snap, src/modules/header/desktopNavigation/accountLinks/__snapshots__/desktopAccountLinks.test.js.snap, src/modules/header/desktopNavigation/accountLinks/desktopAccountLinks.js, src/modules/header/desktopNavigation/accountLinks/desktopAccountLinks.test.js, src/modules/header/desktopNavigation/desktopNavigation.js, src/modules/header/desktopNavigation/megaMenu/megaMenuSection.js, src/modules/header/header.js, src/modules/header/header.md, src/modules/header/mobileNavigation/__snapshots__/mobileNavigation.test.js.snap, src/modules/header/mobileNavigation/accountLinks/mobileAccountLinks.js, src/modules/header/mobileNavigation/mobileNavigation.js
[Delivers: #166532798, #166499247, #166532814, #166499845]
This PR addresses the following issues:
* Navigation says Log In instead of Login
* Incorrect font styles (letter spacing) for Desktop nav (color is
actually incorrect on production, we somehow didn't notice that the link
color is twitter bootstrap blue)
* Bag Notifier Icon is too small (this icon was completely re-worked so
all the logic lives in the SVG)
* Font styles in dropdown menu are incorrect
=> This PR addresses serveral of the Thor style bugs

package-lock.json, package.json, src/components/emailCapture/emailCapture.js, src/components/emailCapture/emailCaptureForm/index.js
With this change we'll validate that the customer enters their email address before submitting the EmailCapture form, we'll also make a couple of styling changes so the component is better integrated with the rest of the page.
https://www.pivotaltracker.com/story/show/165646433
=> Validate email presence for the EmailCapture component

src/components/emailCapture/emailCapture.js
With this change we'll make the white box around the email capture component a bit narrower so it looks a bit better on large screens
https://www.pivotaltracker.com/story/show/165646433
=> Make the email capture box a bit narrower

src/modules/persistent-cart/cartSidebar/cartSidebar.js
With this change we'll update the CartSidebar component so it strikes out the order total indicating that the customer will receive the 'Buy 4 Get 20% off' promotion.
https://www.pivotaltracker.com/story/show/166578243
=> Display promotional pricing on the persistent cart

package-lock.json, package.json, src/components/video/__snapshots__/backgroundVideo.test.js.snap, src/core/video/video.js, src/modules/header/desktopNavigation/__snapshots__/desktopNavigation.test.js.snap, src/modules/header/desktopNavigation/megaMenu/__snapshots__/megaMenuSection.test.js.snap, src/modules/header/mobileNavigation/__snapshots__/mobileNavigation.test.js.snap
This should hopefully fix the annoying uncaught promise error on our homepage.
=> Fixing uncaught dom exception for Video

package-lock.json, package.json, src/components/pressQuotes/pressQuotes.js, src/core/grid/flexRow.js
Fixes* the issue of horizontal scrolling on the homepage
*hopefully
[Delivers #166808423]
=> Homepage scrolling bug

package-lock.json, package.json, src/components/footer/Footer.js
Adds days to business hours in footer.
Thanks!
https://www.pivotaltracker.com/n/projects/2089973/stories/166074831
=> [Finishes #166074831] Add days to business hours

package-lock.json, package.json, src/modules/persistent-cart/cartSidebar/cartSidebar.js, src/modules/persistent-cart/cartSidebar/cartSidebar.md
Sets up the necessary `onClick` events for 'Checkout Started' on thor
[Setup #167068536]
=> 167068536 Checkout started event setup

package-lock.json, package.json, src/components/paymentRequestForm/paymentRequestForm.js, src/components/paymentRequestForm/paymentRequestForm.md, src/modules/persistent-cart/cartSidebar/cartSidebar.js
Need to move this down to the actual stripe-wrapper level `PaymentRequestForm`
=>  move onClickPaymentRequestButton down to paymentRequestForm

src/components/layout/Duet.js, src/components/layout/Quartet.js, src/modules/contentful/contentRow/contentfulContentRow.js, src/modules/contentful/productQuartet/productQuartet.js, src/modules/contentful/responsive/images/contentfulResponsiveImages.base.js, src/modules/contentful/responsive/images/contentfulResponsiveImages.js, src/modules/contentful/touts/contentfulSplitTout.js, src/modules/contentful/touts/contentfulTout.base.js, src/modules/contentful/touts/contentfulTout.js
[#167147482]
This PR addresses some of the styling issues that were plaguing the
mobile view of the homepage.
=> Updating some styles for mobile homepage

src/components/images/slider/slider.js, src/modules/contentful/productQuartet/productQuartet.js, src/modules/contentful/responsive/images/contentfulResponsiveImages.base.js, src/modules/contentful/responsive/images/contentfulResponsiveImages.js, src/modules/images/__snapshots__/gallery.test.js.snap, src/modules/productTile/productTile.base.js, src/modules/productTile/productTile.js, src/modules/productTile/productTile.test.js
[#167157526]
This PR addresses some of the styling issue that were occuring in the
ProductTile compontent includeing the text and the mobile slider
interface.
=> Updating styles for ProductTile

src/modules/contentful/touts/contentfulTout.js
=> Fixing alignment of button

package.json, src/components/footer/Footer.js
Fixes "Subscribe + Save" link in footer. Directs link to the Subscribe and Save page.
Yes - Will create PR in Thor.
- [ Delivers #167296933]
- https://www.pivotaltracker.com/n/projects/2089973/stories/167296933
=> 167296933 subscribe and save footer fix

package-lock.json, package.json, src/modules/contentful/assetLink/contentfulAssetLink.js
=> 167297279 Asset link target bug

package-lock.json, package.json, src/modules/contentful/contentRow/contentfulContentRow.js
=> 167301619 Split tout should stack on iPad view

package-lock.json, package.json, src/modules/contentful/contentRow/contentfulContentRow.js
=> 167301619 iPad split tout fix v2 (double duet)

src/components/header/desktopHeader/headerLink/headerLink.js, src/components/layout/TrioWithLead.js, src/core/breakpoints/index.js, src/core/icons/BagIcon.js, src/core/theme/mediaQueries.js, src/core/theme/theme.js, src/modules/header/desktopNavigation/accountLinks/desktopAccountLinks.js, src/modules/header/desktopNavigation/accountLinks/desktopAccountLinks.md, src/modules/header/desktopNavigation/desktopNavigation.js, src/modules/header/header.js, src/modules/header/header.md, src/modules/header/mobileNavigation/mobileNavigation.js, src/utils/browser-detection.js
[#167265362, #167326548]
This PR addresses some of the styling inconsistencies for the website
navigation. It also includes a fix that was preventing the account links
from being clickable.
=> #167265362/navigation styling fixes

src/components/header/desktopHeader/accountLinks/subMenu.js, src/modules/header/desktopNavigation/accountLinks/desktopAccountLinks.js, src/modules/header/desktopNavigation/accountLinks/desktopAccountLinks.md, src/modules/header/header.md
Currently when a user signs out on Thor, the submenu remains open and
gets put into an odd state. This code change will collapse the submenu
when a user clicks the link to signout.
=> Modifying the signOut function to close submenu

src/components/layout/Solo.js, src/components/layout/TrioWithLead.js, src/core/grid/flexRow.js, src/modules/contentful/contentRow/contentfulContentRow.js
[#167180163]
Updating the Layouts for the Split Tout and the Trio With Lead to mimic
the style on quark-ui.
=> Updating style for Duet, Trio With Lead

src/modules/contentful/touts/contentfulTout.js, src/modules/contentful/touts/contentfulTout.test.js
[#167329978]
Updating the alignment of the buttons so that they render correctly on
Safari.
=> Updating the tout hero position

package-lock.json, package.json, src/modules/productTile/productTile.base.js
=> 167379136 ProductTile relative link

package-lock.json, package.json, src/core/icons/Chevron.js
=> 167056573 Adding padding, fixing color & hover state on Chevron

package-lock.json, package.json, src/components/customerQuotes/customerQuotes.js
Converts from animated to static confetti.
Frame picked by Rina and uploaded to Cloudinary.
Should we delete old images on Cloudinary?
- https://github.com/rocketsofawesome/quark-ui/pull/2516
- https://github.com/rocketsofawesome/thor/pull/54
- [Fixes #167408608]
- https://pivotaltracker.com/n/projects/2089973/stories/167408608
=> [Fixes #167408608] Convert to static confetti

package-lock.json, package.json, src/modules/contentful/responsive/images/contentfulResponsiveImages.base.js
Attempt @ using @mealeyst's original code to try and avoid my hacky & imperfect Thor version of this. Reference: https://github.com/rocketsofawesome/mirage/commit/834a074c38025282fbb833cf574401253671a6ee#diff-6369b55c25ee2b3a2417c6220ce088feR13
[#167404380]
=> 167404380 Preset div height based on image pulled

src/components/images/slider/slider.base.js
Able to pass `lazyLoad` option to slickslider and not its children.
=> Lazy load functionality for slider

package-lock.json, package.json, src/components/social-media/instagram.js
Makes Instagram animation static.
New image was added to Cloudinary to accomplish this.
- `quark-ui` PR
- https://github.com/rocketsofawesome/thor/pull/64
- [Finishes #167491962]
- https://www.pivotaltracker.com/n/projects/2089973/stories/167491962
=> [Finishes #167491962] Make Instagram animation static

package-lock.json, package.json, src/components/clotheslineAnimation/clotheslineAnimation.js
Removes animation from clothesline.
Single change in `clotheslineAnimation.js`.
- https://github.com/rocketsofawesome/thor/pull/tba
- [Finishes #167491910]
- https://www.pivotaltracker.com/n/projects/2089973/stories/167491910
=> [Finishes #167491910] Make clothesline static

package-lock.json, package.json
Since `react-slick` hasn't been updated (meaningfully) in a while & this was an already standing issue on their repo, I added in the fix myself in a forked version.
https://github.com/rocketsofawesome/react-slick
[Delivers #167463413]
=> 167463413 Mobile users tap twice for image link

package-lock.json, package.json, src/core/typography/H1.js, src/templates/outfits/outfitsListing.js
Creates mobile breakpoint for font-size in `H1` styled component.
Creates mobile breakpoint for margins in `outfitsListing`.
Quark UI - tbd
- [Delivers #167623464]
- https://www.pivotaltracker.com/n/projects/2089973/stories/167623464
=> Update mobile styling for h1 and outfitslisting header

package-lock.json, package.json, src/templates/outfits/outfitsListing.js
Sets margins for `OutfitsListing` header based on Rina's specs for online and mobile.
Dependent on changes in Quark UI tbd.
- [Finishes #167623464] 
- https://www.pivotaltracker.com/n/projects/2089973/stories/167623464
=> [Finishes #167623464] Sets margins for OutfitsListing header

src/components/inputs/CheckboxButton/CheckboxButton.base.js, src/components/inputs/CheckboxButton/CheckboxButton.js, src/components/inputs/CheckboxButton/CheckboxButton.md, src/components/inputs/CheckboxButton/CheckboxButton.test.js
=> Adding the checkbox button for gender filter

package-lock.json, package.json, src/templates/outfits/outfitsListing.js
Adds back in left and right margins to `roa-outfits-header`. 
[#167623464]
=> Add left right margins to outfits listing header

package-lock.json, package.json, src/components/images/slider/slider.base.js, src/core/image/inlineImage.js
Reverts rocketsofawesome/mirage#140
=> Revert "[Fixes #167408546] Fix visibility of secondary photos"

package-lock.json, package.json, src/core/icons/SearchIcon.js, src/modules/header/desktopNavigation/desktopNavigation.js, src/modules/header/mobileNavigation/mobileNavigation.js, src/modules/searchModal/searchModal.js
Sends `showSearch` directly from Thor. Instead of consuming from Mirage.
- [Finishes #167715843]
- https://www.pivotaltracker.com/n/projects/2089973/stories/167715843
=> [Finishes #167715843] Send showSearch directly from Thor

package-lock.json, package.json, src/components/footer/Footer.js, src/core/icons/BagIcon.js, src/core/icons/SearchIcon.js, src/core/theme/fontFamilies.js, src/modules/contentful/touts/contentfulTout.base.js, src/modules/contentful/touts/contentfulTout.js, src/modules/header/desktopNavigation/desktopNavigation.js, src/modules/header/mobileNavigation/mobileNavigation.js, src/modules/searchModal/searchModal.js
Improves design for search feature on Thor.
General design improvements.
- [Finishes #167684087]
- https://www.pivotaltracker.com/n/projects/2089973/stories/167684087
=> [#167684087] Improve design for search feature

package-lock.json, package.json, src/components/inputs/Checkbox/Checkbox.js, src/components/inputs/Checkbox/Checkbox.md
Makes changes to `CheckboxBase` used in the gender filter.
Dependent on PRs in Quark, Quark UI, and Thor 
- [Delivers #164499087]
- https://www.pivotaltracker.com/n/projects/2089973/stories/164499087
=> 167290680 gender filter redesign

package-lock.json, package.json, src/core/icons/Logo/Logo.base.js, src/modules/contentful/touts/contentfulTout.base.js, src/modules/contentful/touts/contentfulTout.js, src/modules/header/desktopNavigation/desktopNavigation.js, src/modules/header/mobileNavigation/mobileNavigation.js, src/modules/outfits/outfitSizePicker/outfitSizePicker.js, src/modules/searchModal/searchModal.js
Fixes search bugs.
Styling and usability.
- [Finishes #167812370]
- https://www.pivotaltracker.com/n/projects/2089973/stories/167812370
=> [Finishes #167812370] Fix search bugs

package-lock.json, src/components/animatedIcons/animatedCloudC.js, src/components/clotheslineAnimation/clotheslineAnimation.js, src/components/header/promos/shop/persistantPricing/persistantPricing.js, src/components/inputs/Checkbox/Check.base.js, src/components/inputs/Checkbox/Checkbox.js, src/components/inputs/Checkbox/Rect.base.js, src/components/inputs/CheckboxButton/CheckboxButton.base.js, src/components/inputs/CheckboxButton/CheckboxButton.js, src/components/layout/FullBleed.js, src/components/layout/Solo.js, src/components/layout/TrioWithLead.js, src/modules/contentful/responsive/images/contentfulResponsiveImages.base.js, src/modules/header/header.js, src/modules/persistent-cart/cartSidebar/cartSidebar.js, src/modules/persistent-cart/cartSidebar/cartSidebar.md, src/modules/productTile/productTile.js
With this change we'll ensure that the original order total is displayed in the persistent cart and it's striked through so customers know that a promotion is being applied to their order.
https://www.pivotaltracker.com/story/show/167810033
=> Display original total when a promotion is applied

package-lock.json, package.json, src/components/header/mobileHeader/mobileHeader.js, src/core/icons/Logo/Logo.base.js, src/modules/header/mobileNavigation/mobileNavigation.js
Increases navigation logo size on mobile.
Increases padding between search and bag icons on mobile.
- [Finishes #167840622]
- https://www.pivotaltracker.com/n/projects/2089973/stories/167840622
=> [Finishes #167840622] Increase navigation logo size on mobile

package-lock.json, package.json, src/modules/contentful/touts/contentfulTout.base.js, src/modules/contentful/touts/contentfulTout.js, src/modules/header/desktopNavigation/defaultProps.js, src/modules/layout/main.js
Adds suggestions to empty search page.
Dependent on Thor PR TBD.
- [Finishes #167899911]
- https://www.pivotaltracker.com/n/projects/2089973/stories/167899911
=> [Finishes #167899911] empty search page

package-lock.json, package.json, src/modules/contentful/touts/contentfulTout.base.js, src/modules/contentful/touts/contentfulTout.js
Displays suggestion-search only when products not found.
Reduces white space below empty search results.
- [Finishes #167899911]
- https://www.pivotaltracker.com/n/projects/2089973/stories/167899911
=> [Finishes #167899911] Improve empty search page styling

package-lock.json, package.json, src/core/typography/H1.js, src/core/typography/H2.js
=> 167982465 Desktop & mobile H2 styling

package-lock.json, package.json, src/components/layout/TrioWithLead.js
Vertically align right column of `roa-trio-with-lead-wrapper` with left column.
Especially on desktop view, right column was much taller than left.
- [Finishes #168113928]
- https://www.pivotaltracker.com/n/projects/2089973/stories/168113928
=> [#168113928] Align vertically roa-trio

package-lock.json, package.json, src/components/valuePropSection/defaultProps.js, src/components/valuePropSection/valuePropSection.js
Updates text of first value prop section.
Updates `font-size` of value prop heading.
Removes `margin-bottom` of last sections of value prop, based on screen size.
- [Finishes #168176115]
- https://www.pivotaltracker.com/n/projects/2089973/stories/168176115
=> [#168176115] Improve brand value prop on PDP

package-lock.json, package.json, src/components/header/status/status.js
=> 168433836 Status bar mobile sizing

package-lock.json, package.json, src/components/confetti/Confetti.js, src/modules/persistent-cart/cartSidebar/cartSidebar.js, src/modules/persistent-cart/progressBar/progressBar.js, src/modules/persistent-cart/progressBarText/progressBarText.js
With this change we'll add some copy to the bottom of the cart sidebar to let customers know they'll get free shipping on orders over $50.
We'll also update the copy used in the ProgressBarText to better reflect the evergreen promo savings that the customer will get.
We'll also fix a bug were adding 4+ items to the bag introduced horizontal scrolling on the sidebar.
*Bonus* we'll add the particleSpeed prop to the `Confetti` component so we can control how fast confetti particles fall down.
https://www.pivotaltracker.com/story/show/168467173
https://www.pivotaltracker.com/story/show/168513679
https://www.pivotaltracker.com/story/show/168731027
https://www.pivotaltracker.com/story/show/168732103
=> Progress bar fixes

package-lock.json, package.json, src/modules/persistent-cart/progressBarText/progressBarText.js
Changes copy for progress bar with 4+ items in bag.
- [#168467173]
- https://www.pivotaltracker.com/story/show/168467173
=> 168467173 progress bar copy fix

package-lock.json, package.json, src/modules/persistent-cart/cartSidebar/cartSidebar.js, src/modules/persistent-cart/cartSidebar/cartSidebar.md
Updates copy and styling of the gift link in `cartSidebar`.
Update Mirage version on Quark UI and Thor
- [ch5641]
- https://app.clubhouse.io/rockets/story/5641/customer-reads-gifting-link-as-send-as-a-gift-in-checkout-bag
=> [ch5641] Update copy and styling of gift link

package-lock.json, package.json, src/modules/persistent-cart/persistentCartProduct/persistentCartProduct.js
Adds `FinalSale` to `PersistentCartProduct`.
Updates `version` to `0.1.409`.
- [ch5894]
- https://app.clubhouse.io/rockets/story/5894/customer-reads-that-black-friday-cyber-monday-sale-item-is-final-sale-in-bag
=> [ch5894] Add FinalSale to PersistentCartProduct

package-lock.json, package.json, src/components/giftModal/GiftModal.js
Changes asterisk placement in gift modal copy.
[ch5915] https://app.clubhouse.io/rockets/story/5915/gifting-pop-up-copy-is-more-on-brand-copy-edit
=> Gift modal copy

package-lock.json, package.json, src/components/footer/Footer.js
Removes FAQ link from footer, since it has same destination as Help link.
Updates Mirage to `0.1.414`.
- [ch5967]
- https://app.clubhouse.io/rockets/story/5967/subscribers-pay-20-service-fee
=> [ch5967] Remove FAQ link from footer

package-lock.json, package.json, src/components/inputs/InputSmall/InputSmall.js, src/components/inputs/InputSmall/InputSmall.md, src/components/inputs/InputSmall/index.js, src/components/inputs/XCheckbox/X.base.js, src/components/inputs/XCheckbox/XCheckbox.js, src/components/inputs/XCheckbox/XCheckbox.md, src/components/inputs/XCheckbox/XCheckboxSVG.base.js, src/components/inputs/XCheckbox/XRect.base.js, src/components/inputs/index.js
Adds new input field components `XCheckbox` (checkbox with an "x") and `InputSmall` (slimmer version of `Input` with different styling of placeholder). This is for use in the waitlist form on Thor.
[ch5968]
https://app.clubhouse.io/rockets/story/5968/guests-can-request-to-get-alert-when-items-are-back-in-stock
=> [ch5968] Add new inputs XCheckbox and InputSmall for use in waitlist form

package-lock.json, package.json, src/components/inputs/Checkbox/Checkbox.js
Ensures Checkbox component has a label if it is provided as a prop.
In a redux form Field we should be able to pass label text as a prop to the nested checkbox component.
Update Mirage on Quark UI
[ch6197]
https://app.clubhouse.io/rockets/story/6197/shop-customers-upgrading-to-subscription-should-see-label-with-text-message-opt-in-checkbox
=> [ch6197] Ensure Checkbox has a label if provided as a prop

package-lock.json, package.json, src/modules/searchModal/searchModal.js
Updates search suggestion copy and image on search modal.
Update Mirage version on Thor
Separate change for Quark UI
[ch6366]
https://app.clubhouse.io/rockets/story/6366/customers-see-spring-search-terms-on-search-overlay
[ch5986]
https://app.clubhouse.io/rockets/story/5986/customers-see-spring-image-on-search-overlay
=> [ch6366][ch5986] Update copy and image on SearchModal

package-lock.json, package.json, src/modules/searchModal/searchModal.js
Change suggested search term from "CrazySoft Crew" to "soft" per copywriting change.
Update Mirage version.
=> Search term update

package-lock.json, package.json, src/components/giftModal/GiftModal.js
Adds final sale copy to gift modal.
[ch6776]
https://app.clubhouse.io/rockets/story/6776/customer-learns-that-free-gift-exchanges-exclude-final-sale-items
=> Ch6776 gift modal final sale

package-lock.json, package.json, src/modules/outfits/outfitSizePicker/outfitSizePicker.js, src/modules/outfits/outfitSizePicker/outfitSizePicker.md
Show evergreen promo and sale prices on outfitSizePicker
PR in Thor and Quark
[ch6768]
https://app.clubhouse.io/rockets/story/6768/customer-sees-promo-price-of-items-on-outfits-detail-pages
=> Ch6768 outfits promo price

src/modules/persistent-cart/progressBar/progressBar.js
Makes the gray in ProgressBar darker.
[ch6783]
https://app.clubhouse.io/rockets/story/6783/customer-sees-progress-against-evergreen-promo-on-plp
=> [ch6783] Make gray in ProgressBar darker

package-lock.json, package.json, src/modules/persistent-cart/progressBar/progressBar.js
Lower z-index so ProgressBar cloud won't appear on top of header or megamenu.
[ch6783]
https://app.clubhouse.io/rockets/story/6783/customer-sees-progress-against-evergreen-promo-on-plp
=> Ch6783 progress bar styling

package-lock.json, package.json, src/components/giftModal/GiftModal.js, src/components/header/promos/shop/persistantPricing/persistantPricing.js, src/components/valuePropSection/defaultProps.js, src/modules/outfits/outfitSizePicker/outfitSizePicker.js, src/modules/persistent-cart/cartSidebar/cartSidebar.js, src/modules/persistent-cart/progressBarText/progressBarText.js, src/modules/productTile/productPrice/productPrice.js
Changes evergreen promo to 6 for 25% off
* Requires code change on Thor.
* On Quark admin, set the existing 4 for 20% promo to be expired and create a new promo of 6 for 25% (this way it should update the promo on existing bags)
[ch6853]
https://app.clubhouse.io/rockets/story/6853/customers-can-purchase-6-items-for-25-off
=> [ch6853] Change evergreen promo to 6 for 25% off

package-lock.json, package.json, src/components/header/desktopHeader/accountLinks/subMenu.js, src/modules/header/header.js, src/modules/header/mobileNavigation/menuDrawer/menuDrawer.js, src/modules/searchModal/searchModal.js
Increases z-index on header and search components to accommodate the addition of the size dropdown on PDPs.
[ch6806]
https://app.clubhouse.io/rockets/story/6806/customer-sees-pdp-size-selector-as-drop-down
=> Increase z-index on header and search components

package-lock.json, package.json, src/modules/searchModal/searchModal.js
Updates suggested search terms for summer season
Update Mirage version on Thor
[ch6865]
https://app.clubhouse.io/rockets/story/6865/customer-sees-summer-themed-suggested-search-terms
=> [ch6865] Update suggested search terms for summer season

package-lock.json, package.json, src/modules/persistent-cart/persistentCartProduct/persistentCartProduct.js, src/utils/pricing.js
Shows line items in bag with evergreen promo and price adjustments the same way we do in checkout.
[ch6971]
https://app.clubhouse.io/rockets/story/6971/customer-sees-evergreen-promo-pricing-in-bag-when-eligible
=> [ch6971] Show line item adjusted prices in bag

package-lock.json, package.json, src/modules/persistent-cart/persistentCartProduct/persistentCartProduct.js
Adds source to Segment event for removing items from bag.
[ch7008]
https://app.clubhouse.io/rockets/story/7008/event-tracking-fires-on-order-editing-in-bag
=> [ch7008] Add source to product removed event

package-lock.json, package.json, src/components/footer/Footer.js
Removes phone number from footer (Thor and Quark UI) to lessen the call load on the CX team.
[ch7219]
https://app.clubhouse.io/rockets/story/7219/remove-phone-number-from-footer
=> [ch7219] Remove phone number from footer

package-lock.json, package.json, src/core/icons/Logo/__snapshots__/GrayLogo.test.js.snap, src/core/icons/Logo/__snapshots__/Logo.test.js.snap, src/core/icons/Logo/__snapshots__/NavyLogo.test.js.snap, src/core/icons/Logo/__snapshots__/WhiteLogo.test.js.snap, src/core/icons/Spinner/__snapshots__/GraySpinner.test.js.snap, src/core/typography/H3.js, src/core/typography/H4.js, src/core/typography/H5.js, src/core/typography/H6.js, src/core/typography/P.js, src/index.js, src/modules/complete-account/__snapshots__/SubscriptionShipping.test.js.snap, src/modules/contentful/slider/contentfulSlider.js, src/modules/header/desktopNavigation/__snapshots__/desktopNavigation.test.js.snap, src/modules/header/desktopNavigation/desktopNavigation.js, src/modules/header/header.js, src/modules/header/mobileNavigation/mobileNavigation.js, src/modules/images/__snapshots__/gallery.test.js.snap, src/modules/productTile/colorPicker/colorsInterface.js, src/modules/social-media/__snapshots__/instagramRegion.test.js.snap
With this change we'll add support for text alignment on header elements (H3, H4, H5 and H6) through the `align` property.
This change should also fix a couple of warnings generated when using mirage components.
=> Support text alignment on heading elements

package-lock.json, package.json, src/components/inputs/Checkbox/Checkbox.js, src/components/inputs/Checkbox/Checkbox.test.js
With this change we'll fix a bug that was causing checkboxes to disappear depending on the screen size.
=> Fix checkboxes going missing in different screen sizes

package-lock.json, package.json, src/core/typography/H3.js, src/core/typography/H4.js, src/core/typography/H5.js, src/core/typography/H6.js, src/core/typography/P.js
With this change we'll default alignment on typography elements
to inherit so they blend nicely with their context.
=> Default alignment on typography elements to inherit

package-lock.json, package.json, src/modules/searchModal/searchModal.js
Changes search terms for winter appropriate clothing
[ch7810]
https://app.clubhouse.io/rockets/story/7810/ecommerce-customers-see-seasonally-appropriate-suggested-search-term-copy
=> [ch7810] Change search terms for winter appropriate clothing

src/components/images/slider/slider.base.js, src/components/images/slider/slider.md, src/modules/productTile/defaultProps.js, src/utils/shotSorter.js
With this change we'll start displaying badges on top of product shots whenever they have a badge associated with them
this allows us to grab the customer's eye and highlight a feature of the product.
https://app.clubhouse.io/rockets/story/7984/customers-see-that-some-items-in-black-friday-10-sale-are-only-5
=> Overlay badges on shots

package-lock.json, package.json, src/components/footer/Footer.js, src/components/footer/Footer.md
With this change we'll update the `Footer` component so it receives two props that better match the way the referral program works where the referrer and referred user get different amounts.
https://app.clubhouse.io/rockets/story/8049/subscriber-sees-referral-offer-value-as-give-50-get-20
=> Update footer copy so it matches the new referral program

package-lock.json, package.json, src/components/footer/Footer.js
Updates referral copy in footer with new marketing messaging.
https://app.clubhouse.io/rockets/story/8135/customer-reads-consistent-referral-cta-in-footer
=> [ch8135] Update referral copy in footer

package-lock.json, package.json, src/components/inputs/Buttons/Button/ButtonLink.js, src/modules/contentful/slider/contentfulSlide.js, src/modules/contentful/slider/defaultProps.js
With this change we'll fix a couple of warnings caused by the ContentfulSlider and the CartSidebar components.
=> Fix warnings related to the ContentfulSlider and the CartSidebar

package-lock.json, package.json, src/components/datepicker/Datepicker.js, src/components/datepicker/Datepicker.md, src/components/inputs/Input/Input.js, src/components/inputs/Input/Input.md, src/components/inputs/radioButtons/rectangularRadioButton.js, src/components/inputs/radioButtons/rectangularRadioButton.md
With this change we'll add the kind prop to the `RectangularRadioButton`, `Input` and `Datepicker` components so we
can support styles for the mini quiz.
https://app.shortcut.com/rockets/story/8909/customer-sees-mini-style-guide-applied-to-quiz
=> Add mini variant to form inputs

package-lock.json, package.json, src/components/curvedText/curvedText.js, src/components/curvedText/curvedText.md
With this change we'll update the styling of the CurvedText component so it matches the style guide for mini.
=> Use the header font family for curved text

src/components/inputs/Buttons/Button/Button.js, src/core/theme/colors.js, src/core/theme/mini/miniColors.js
This PR reenables theming on the Button component. It turns out there is *one* page where we actually do use the mini theme on it.
=> Reenabe theme on Button component

src/core/grid/flexRow.js, src/core/grid/flexRow.md
This PR allows the wrap and columnGap props on FlexRows to be changed depending on the size of the viewport
=> Allow for different wrap and columnGap props depending on viewport
